/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel;

import classes.MakeReservation;
import classes.Room;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author mahdi
 */
public class Bill extends javax.swing.JDialog {

    /**
     * Creates new form BillDialog
     */
    private Connection con=null;
    public Bill(java.awt.Frame parent, boolean modal,int reserv_id) {
        super(parent, modal);
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            this.con=DriverManager.getConnection(Hotel.getUrl());
            Statement stat=con.createStatement();
            ResultSet set=stat.executeQuery("Select DATEDIFF(day,check_out,check_in) FROM reservation WHERE reserv_id="+reserv_id);
            if(set.next())
            {
                int days=set.getInt(1);
                set=stat.executeQuery("Select * FROM make_reservation WHERE reserv_id="+reserv_id);
                if(set.next())
                {   
                    MakeReservation make=new MakeReservation(set.getInt(1),set.getInt(2),set.getInt(2),set.getInt(4));
                    set=stat.executeQuery("Select * FROM room WHERE room_id="+make.getRoom_id());
                    if(set.next())
                    {
                        Room room=new Room(set.getInt(1),set.getInt(2),set.getInt(3),set.getString(4));
                        set=stat.executeQuery("SELECT pricePerNight FROM price WHERE type='"+room.getType()+"'");
                        if(set.next())
                        {
                            int price=set.getInt(1);
                            set=stat.executeQuery("SELECT pricePerNight FROM price WHERE type='Entry'");
                            if(set.next())
                            {
                                int entry=set.getInt(1);
                                int total=entry+days*price;
                                initComponents();
                                this.billTextArea
                                    .setText("Entry : "+entry
                                            +"\n#################"
                                            +"\nRoom Type : "+room.getType()
                                            +"\nPrice per day : "+price
                                            +"\ndays : "+days
                                            +"\nRoom Total Price : "+(total-entry)
                                            +"\n#################"
                                            +"\nTotal : "+total);
                            }
                        }
                    }
                }
            }
        con.close();
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this,"Missing SQLServerDriver!","",JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(CheckOut.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        billTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BILL");

        billTextArea.setEditable(false);
        billTextArea.setColumns(20);
        billTextArea.setRows(5);
        jScrollPane1.setViewportView(billTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea billTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
