/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hotel;

import classes.JTableUtilities;
import classes.MyTableModel;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mahdi
 */
public class Customers extends javax.swing.JPanel {

    
    private String[] identifier={"ID","NAME","LAST NAME","PHONE NUMBER","EMAIL"};
    private Connection con;
    private String search;
    private BufferedImage backgroundImage;
    @Override
    public void paintComponent(Graphics grphcs) {
        super.paintComponent(grphcs); 
        grphcs.drawImage(backgroundImage, 0,0,this.getWidth(),this.getHeight(), this);
    }
    public Customers() {
        try {
            this.backgroundImage=ImageIO.read(new File("src\\images\\home.jpg"));
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            this.con=DriverManager.getConnection(Hotel.getUrl());
            Statement stat=con.createStatement();
            search="cust_id";
            MyTableModel cust=new MyTableModel();
            this.customerTable.setModel(cust);
            cust.setColumnIdentifiers(identifier);
            ResultSet set=stat.executeQuery("SELECT * FROM customer ORDER BY cust_id DESC");
            while(set.next())
            {
                Object[] row={set.getInt(1),set.getString(2),set.getString(3),set.getString(4),set.getString(5)};
                cust.addRow(row);
            }
            JTableUtilities.setCellsAlignment(customerTable, SwingConstants.CENTER);
            this.con.close();
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this,"Missing SQLServerDriver!","",JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Connection Error!","",JOptionPane.ERROR_MESSAGE);
        }
        
    }

    public ButtonGroup getSeachGroup() {
        return seachGroup;
    }

    public JTextField getSearchTextField() {
        return searchTextField;
    }

    public JRadioButton getIdSearchRadioButton() {
        return idSearchRadioButton;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        sort1Group = new javax.swing.ButtonGroup();
        sort2Group = new javax.swing.ButtonGroup();
        seachGroup = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();
        searchPanel = new javax.swing.JPanel();
        searchByLabel = new javax.swing.JLabel();
        nameSearchRadioButton = new javax.swing.JRadioButton();
        lastNameSearchRadioButton = new javax.swing.JRadioButton();
        idSearchRadioButton = new javax.swing.JRadioButton();
        emailSearchRadioButton = new javax.swing.JRadioButton();
        phoneNumberSeachRadioButton = new javax.swing.JRadioButton();
        searchLabel = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        customerTable.getTableHeader().setBackground(new Color(255,255,255,100));
        customerTable.setAutoCreateRowSorter(true);
        customerTable.setFillsViewportHeight(true);
        customerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        customerTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        customerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rev(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rev(evt);
            }
        });
        jScrollPane1.setViewportView(customerTable);
        customerTable.getTableHeader().setReorderingAllowed(false);

        searchPanel.setBackground(new Color(255,255,255,100));
        searchPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Search : "));

        searchByLabel.setText("Search By : ");

        nameSearchRadioButton.setBackground(new Color(0,0,0,0)
        );
        seachGroup.add(nameSearchRadioButton);
        nameSearchRadioButton.setText("Name");
        nameSearchRadioButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ref(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ref(evt);
            }
        });
        nameSearchRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rep(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rep(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rep(evt);
            }
        });
        nameSearchRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameSearchRadioButtonActionPerformed(evt);
            }
        });

        lastNameSearchRadioButton.setBackground(new Color(0,0,0,0));
        seachGroup.add(lastNameSearchRadioButton);
        lastNameSearchRadioButton.setText("Last Name");
        lastNameSearchRadioButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ref(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ref(evt);
            }
        });
        lastNameSearchRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rep(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rep(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rep(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rep(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rep(evt);
            }
        });
        lastNameSearchRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameSearchRadioButtonActionPerformed(evt);
            }
        });

        idSearchRadioButton.setBackground(new Color(0,0,0,0));
        seachGroup.add(idSearchRadioButton);
        idSearchRadioButton.setSelected(true);
        idSearchRadioButton.setText("ID");
        idSearchRadioButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ref(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ref(evt);
            }
        });
        idSearchRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rep(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rep(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rep(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rep(evt);
            }
        });
        idSearchRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idSearchRadioButtonActionPerformed(evt);
            }
        });

        emailSearchRadioButton.setBackground(new Color(0,0,0,0));
        seachGroup.add(emailSearchRadioButton);
        emailSearchRadioButton.setText("Email");
        emailSearchRadioButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                rep(evt);
            }
        });
        emailSearchRadioButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ref(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ref(evt);
            }
        });
        emailSearchRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rep(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rep(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rep(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rep(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rep(evt);
            }
        });
        emailSearchRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailSearchRadioButtonActionPerformed(evt);
            }
        });

        phoneNumberSeachRadioButton.setBackground(new Color(0,0,0,0));
        seachGroup.add(phoneNumberSeachRadioButton);
        phoneNumberSeachRadioButton.setText("Phone Number");
        phoneNumberSeachRadioButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                rep(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                rep(evt);
            }
        });
        phoneNumberSeachRadioButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ref(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ref(evt);
            }
        });
        phoneNumberSeachRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rep(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rep(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rep(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rep(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rep(evt);
            }
        });
        phoneNumberSeachRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberSeachRadioButtonActionPerformed(evt);
            }
        });

        searchLabel.setText("Search : ");

        searchTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchTextFieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addComponent(searchByLabel)
                        .addGap(18, 18, 18)
                        .addComponent(idSearchRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(nameSearchRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(lastNameSearchRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(emailSearchRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(phoneNumberSeachRadioButton)
                        .addGap(0, 53, Short.MAX_VALUE))
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addComponent(searchLabel)
                        .addGap(18, 18, 18)
                        .addComponent(searchTextField)))
                .addGap(10, 10, 10))
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchByLabel)
                    .addComponent(idSearchRadioButton)
                    .addComponent(nameSearchRadioButton)
                    .addComponent(lastNameSearchRadioButton)
                    .addComponent(emailSearchRadioButton)
                    .addComponent(phoneNumberSeachRadioButton))
                .addGap(18, 18, 18)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(searchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lastNameSearchRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameSearchRadioButtonActionPerformed
        this.search="cust_lastName";
    }//GEN-LAST:event_lastNameSearchRadioButtonActionPerformed

    private void phoneNumberSeachRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberSeachRadioButtonActionPerformed
        this.search="cust_PhoneNumber";
    }//GEN-LAST:event_phoneNumberSeachRadioButtonActionPerformed

    private void emailSearchRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailSearchRadioButtonActionPerformed
        this.search="cust_email";
    }//GEN-LAST:event_emailSearchRadioButtonActionPerformed

    private void idSearchRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idSearchRadioButtonActionPerformed
        this.search="cust_id";
    }//GEN-LAST:event_idSearchRadioButtonActionPerformed

    private void nameSearchRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameSearchRadioButtonActionPerformed
        this.search="cust_name";
    }//GEN-LAST:event_nameSearchRadioButtonActionPerformed

    private void searchTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTextFieldKeyTyped
        try {
            this.con=DriverManager.getConnection(Hotel.getUrl());
            Statement stat=con.createStatement();
            DefaultTableModel cust=new DefaultTableModel();
            this.customerTable.setModel(cust);
            cust.setColumnIdentifiers(identifier);
            String word;
            if(!Character.isISOControl(evt.getKeyChar()))
            {
                word=this.searchTextField.getText()+evt.getKeyChar();
            }
            else
            {
                word=this.searchTextField.getText();
            }
            ResultSet set=stat.executeQuery("SELECT * FROM customer "
                    + "WHERE "+this.search+" LIKE '%"+word+"%' ORDER BY cust_id DESC");
            while(set.next())
            {
                Object[] row={set.getInt(1),set.getString(2),set.getString(3),set.getString(4),set.getString(5)};
                cust.addRow(row);
            }
            JTableUtilities.setCellsAlignment(customerTable, SwingConstants.CENTER);
            this.revalidate();
            this.repaint();
            this.con.close();
        } catch (SQLException ex) {
            Logger.getLogger(CheckIn.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchTextFieldKeyTyped

    private void ref(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ref
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_ref

    private void rep(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rep
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_rep

    private void rev(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rev
        // TODO add your handling code here:
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_rev

    public JTable getCustomerTable() {
        return customerTable;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTable customerTable;
    private javax.swing.JRadioButton emailSearchRadioButton;
    private javax.swing.JRadioButton idSearchRadioButton;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton lastNameSearchRadioButton;
    private javax.swing.JRadioButton nameSearchRadioButton;
    private javax.swing.JRadioButton phoneNumberSeachRadioButton;
    private javax.swing.ButtonGroup seachGroup;
    private javax.swing.JLabel searchByLabel;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JTextField searchTextField;
    private javax.swing.ButtonGroup sort1Group;
    private javax.swing.ButtonGroup sort2Group;
    // End of variables declaration//GEN-END:variables

}
