/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hotel;

import classes.JTableUtilities;
import classes.MyTableModel;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mahdi
 */
public class Employees extends javax.swing.JPanel {

    
    private String[] identifier={"ID","NAME","LAST NAME","PHONE NUMBER","EMAIL","SALARY","USERNAME","LASTSEEN"};
    private Connection con;
    private String search;
    private BufferedImage backgroundImage;
    @Override
    public void paintComponent(Graphics grphcs) {
        super.paintComponent(grphcs); 
        grphcs.drawImage(backgroundImage, 0,0,this.getWidth(),this.getHeight(), this);
    }
    public Employees() {
        try {
            this.backgroundImage=ImageIO.read(new File("src\\images\\home.jpg"));
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            this.con=DriverManager.getConnection(Hotel.getUrl());
            Statement stat=con.createStatement();
            search="employee.emp_name";
            MyTableModel emp=new MyTableModel();
            this.employeesTable.setModel(emp);
            emp.setColumnIdentifiers(identifier);
            ResultSet set=stat.executeQuery("SELECT * FROM Employee,has,Log_In "
                    + "WHERE employee.emp_id=has.emp_id and has.username=log_In.username "
                    + "ORDER BY employee.emp_id DESC");
            while(set.next())
            {
                Object[] row={set.getInt(1),set.getString(2),set.getString(3),set.getString(4),set.getString(5),
                set.getDouble(6),set.getString(8),set.getDate(11)};
                emp.addRow(row);
            }
            JTableUtilities.setCellsAlignment(employeesTable, SwingConstants.CENTER);
            this.con.close();
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this,"Missing SQLServerDriver!","",JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(Rooms.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public JTable getEmployeesTable() {
        return employeesTable;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        sort1Group = new javax.swing.ButtonGroup();
        sort2Group = new javax.swing.ButtonGroup();
        seachGroup = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        employeesTable = new javax.swing.JTable();
        searchPanel = new javax.swing.JPanel();
        searchByLabel = new javax.swing.JLabel();
        nameSearchRadioButton = new javax.swing.JRadioButton();
        lastNameSearchRadioButton = new javax.swing.JRadioButton();
        idSearchRadioButton = new javax.swing.JRadioButton();
        emailSearchRadioButton = new javax.swing.JRadioButton();
        phoneNumberSeachRadioButton = new javax.swing.JRadioButton();
        searchLabel = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        userNameRadioButton = new javax.swing.JRadioButton();
        addButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jScrollPane1.setBackground(new Color(0,0,0));

        employeesTable.getTableHeader().setBackground(new Color(255,255,255));
        employeesTable.setAutoCreateRowSorter(true);
        employeesTable.setFillsViewportHeight(true);
        employeesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        employeesTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(employeesTable);
        employeesTable.getTableHeader().setReorderingAllowed(false);

        searchPanel.setBackground(new Color(255,255,255,100));
        searchPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Search : "));

        searchByLabel.setText("Search By : ");

        nameSearchRadioButton.setBackground(new Color(0,0,0,0));
        seachGroup.add(nameSearchRadioButton);
        nameSearchRadioButton.setSelected(true);
        nameSearchRadioButton.setText("Name");
        nameSearchRadioButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                mm(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                mm(evt);
            }
        });
        nameSearchRadioButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ff(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ff(evt);
            }
        });
        nameSearchRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mm(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mm(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mm(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mm(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mm(evt);
            }
        });
        nameSearchRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameSearchRadioButtonActionPerformed(evt);
            }
        });

        lastNameSearchRadioButton.setBackground(new Color(0,0,0,0));
        seachGroup.add(lastNameSearchRadioButton);
        lastNameSearchRadioButton.setText("Last Name");
        lastNameSearchRadioButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                mm(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                mm(evt);
            }
        });
        lastNameSearchRadioButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ff(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ff(evt);
            }
        });
        lastNameSearchRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mm(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mm(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mm(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mm(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mm(evt);
            }
        });
        lastNameSearchRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameSearchRadioButtonActionPerformed(evt);
            }
        });

        idSearchRadioButton.setBackground(new Color(0,0,0,0));
        seachGroup.add(idSearchRadioButton);
        idSearchRadioButton.setText("ID");
        idSearchRadioButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                mm(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                mm(evt);
            }
        });
        idSearchRadioButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ff(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ff(evt);
            }
        });
        idSearchRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mm(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mm(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mm(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mm(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mm(evt);
            }
        });
        idSearchRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idSearchRadioButtonActionPerformed(evt);
            }
        });

        emailSearchRadioButton.setBackground(new Color(0,0,0,0));
        seachGroup.add(emailSearchRadioButton);
        emailSearchRadioButton.setText("Email");
        emailSearchRadioButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                mm(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                mm(evt);
            }
        });
        emailSearchRadioButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ff(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ff(evt);
            }
        });
        emailSearchRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mm(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mm(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mm(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mm(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mm(evt);
            }
        });
        emailSearchRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailSearchRadioButtonActionPerformed(evt);
            }
        });

        phoneNumberSeachRadioButton.setBackground(new Color(0,0,0,0));
        seachGroup.add(phoneNumberSeachRadioButton);
        phoneNumberSeachRadioButton.setText("Phone Number");
        phoneNumberSeachRadioButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                mm(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                mm(evt);
            }
        });
        phoneNumberSeachRadioButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ff(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ff(evt);
            }
        });
        phoneNumberSeachRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mm(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mm(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mm(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mm(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mm(evt);
            }
        });
        phoneNumberSeachRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberSeachRadioButtonActionPerformed(evt);
            }
        });

        searchLabel.setText("Search : ");

        searchTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchTextFieldKeyTyped(evt);
            }
        });

        userNameRadioButton.setBackground(new Color(0,0,0,0));
        seachGroup.add(userNameRadioButton);
        userNameRadioButton.setText("UserName");
        userNameRadioButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                mm(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                mm(evt);
            }
        });
        userNameRadioButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ff(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ff(evt);
            }
        });
        userNameRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mm(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mm(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mm(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mm(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mm(evt);
            }
        });
        userNameRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addComponent(searchByLabel)
                        .addGap(18, 18, 18)
                        .addComponent(idSearchRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(nameSearchRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(lastNameSearchRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(phoneNumberSeachRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(emailSearchRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(userNameRadioButton)
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addComponent(searchLabel)
                        .addGap(18, 18, 18)
                        .addComponent(searchTextField)))
                .addContainerGap())
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchByLabel)
                    .addComponent(idSearchRadioButton)
                    .addComponent(nameSearchRadioButton)
                    .addComponent(lastNameSearchRadioButton)
                    .addComponent(phoneNumberSeachRadioButton)
                    .addComponent(emailSearchRadioButton)
                    .addComponent(userNameRadioButton))
                .addGap(18, 18, 18)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchLabel)
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        addButton.setBackground(new java.awt.Color(255, 255, 255));
        addButton.setText("ADD ");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        editButton.setBackground(new java.awt.Color(255, 255, 255));
        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        deleteButton.setBackground(new java.awt.Color(255, 255, 255));
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(deleteButton)
                        .addGap(18, 18, 18)
                        .addComponent(editButton)
                        .addGap(18, 18, 18)
                        .addComponent(addButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(editButton)
                    .addComponent(deleteButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lastNameSearchRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameSearchRadioButtonActionPerformed
        this.search="employee.emp_lastName";
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_lastNameSearchRadioButtonActionPerformed

    private void phoneNumberSeachRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberSeachRadioButtonActionPerformed
        this.search="employee.emp_PhoneNumber";
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_phoneNumberSeachRadioButtonActionPerformed

    private void emailSearchRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailSearchRadioButtonActionPerformed
        this.search="employee.emp_email";
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_emailSearchRadioButtonActionPerformed

    private void idSearchRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idSearchRadioButtonActionPerformed
        this.search="employee.emp_id";
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_idSearchRadioButtonActionPerformed

    private void nameSearchRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameSearchRadioButtonActionPerformed
        this.search="employee.emp_name";
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_nameSearchRadioButtonActionPerformed

    private void searchTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTextFieldKeyTyped
        try {
            this.con=DriverManager.getConnection(Hotel.getUrl());
            Statement stat=con.createStatement();
            MyTableModel cust=new MyTableModel();
            this.employeesTable.setModel(cust);
            cust.setColumnIdentifiers(identifier);
            String word;
            if(!Character.isISOControl(evt.getKeyChar()))
            {
                word=this.searchTextField.getText()+evt.getKeyChar();
            }
            else
            {
                word=this.searchTextField.getText();
            }
            ResultSet set=stat.executeQuery("SELECT * FROM Employee,has,Log_In "
                    + "WHERE "+this.search+" LIKE '%"+word+"%' "
                            + "and employee.emp_id=has.emp_id and has.username=log_In.username "
                    + "ORDER BY employee.emp_id DESC");
            while(set.next())
            {
                Object[] row={set.getInt(1),set.getString(2),set.getString(3),set.getString(4),set.getString(5),
                set.getDouble(6),set.getString(8),set.getDate(11)};
                cust.addRow(row);
            }
            this.con.close();
        } catch (SQLException ex) {
            Logger.getLogger(CheckIn.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_searchTextFieldKeyTyped

    public JRadioButton getIdSearchRadioButton() {
        return idSearchRadioButton;
    }

    public ButtonGroup getSeachGroup() {
        return seachGroup;
    }

    private void userNameRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameRadioButtonActionPerformed
        this.search="has.username";
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_userNameRadioButtonActionPerformed

    private void mm(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mm
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_mm

    private void ff(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ff
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_ff

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        int row=this.employeesTable.getSelectedRow();
        if(row>=0)
        {
            int id = (int)this.employeesTable.getValueAt(row, 0);
            AddEditEmp edit = new AddEditEmp(Hotel.getHome(),true,id);
            edit.setSize(650,350);
            edit.setLocationRelativeTo(null);
            edit.setVisible(true);
        }
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_editButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        AddEditEmp add = new AddEditEmp(Hotel.getHome(),true);
        add.setSize(650,350);
        add.setLocationRelativeTo(null);
        add.setVisible(true);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_addButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int row=this.employeesTable.getSelectedRow();
        String id=this.employeesTable.getValueAt(row, 0).toString();
        String usename=this.employeesTable.getValueAt(row, 6).toString();
        if(row>=0)
        {
            try {
                if(id.equals("0"))
                {
                    JOptionPane.showMessageDialog(this,"Cannot delete the super admin");
                    return;
                }
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                this.con=DriverManager.getConnection(Hotel.getUrl());
                Statement stat=con.createStatement();
                stat.executeUpdate("Delete From Employee Where emp_id="+id);
                stat.executeUpdate("Delete From Log_IN Where username='"+usename+"'");
                MyTableModel model=(MyTableModel)this.employeesTable.getModel();
                model.removeRow(row);
                con.close();
            } catch (SQLException ex) {
                Logger.getLogger(Employees.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Employees.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_deleteButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JRadioButton emailSearchRadioButton;
    private javax.swing.JTable employeesTable;
    private javax.swing.JRadioButton idSearchRadioButton;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton lastNameSearchRadioButton;
    private javax.swing.JRadioButton nameSearchRadioButton;
    private javax.swing.JRadioButton phoneNumberSeachRadioButton;
    private javax.swing.ButtonGroup seachGroup;
    private javax.swing.JLabel searchByLabel;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JTextField searchTextField;
    private javax.swing.ButtonGroup sort1Group;
    private javax.swing.ButtonGroup sort2Group;
    private javax.swing.JRadioButton userNameRadioButton;
    // End of variables declaration//GEN-END:variables

}
