/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel;

import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author mahdi
 */
public class LoginPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginPanel
     */
    private Image backgroundImage;
    public LoginPanel() {
        initComponents();
        try {
            this.backgroundImage=ImageIO.read(new File("src\\images\\hotel.jpg"));
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    @Override
    public void paintComponent(Graphics grphcs) {
        super.paintComponent(grphcs);
        grphcs.drawImage(backgroundImage, 0,0,this.getWidth(),this.getHeight(), this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t_username = new javax.swing.JTextField();
        t_password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        b_login = new javax.swing.JButton();
        userLogo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        t_username.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        t_username.setToolTipText("");

        t_password.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password:");

        b_login.setBackground(new java.awt.Color(255, 255, 255));
        b_login.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b_login.setText("Log in");
        b_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_loginActionPerformed(evt);
            }
        });

        userLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pass.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hotel.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(t_username, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(userLogo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addComponent(t_password, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b_login)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel4)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(userLogo)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(b_login)
                .addContainerGap(293, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_loginActionPerformed
        // TODO add your handling code here:
        String username =t_username.getText();
        String password =t_password.getText();
        if(username.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Enter your username");
        }
        else if(password.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Enter your password");
        }
        else
        {
            try{
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                try (Connection con = DriverManager.getConnection(Hotel.getUrl())) {
                    Statement st=con.createStatement();
                    ResultSet rs= st.executeQuery("select * from Log_In where UserName='"+username+"'");
                    if(rs.next())
                    {
                        if(rs.getString(2).equals(password))
                        {
                            Hotel.setRole(rs.getString(4));
                            rs= st.executeQuery("select * from has,employee where has.UserName='"+username+"' and has.emp_id=employee.emp_id");
                            rs.next();
                            Hotel.setEmp_id(rs.getInt(1));
                            Hotel.setHome(new Home());
                            Hotel.getHome().setTitle("Hotel Management System-Home-Logged as : "
                                    +rs.getString("emp_name")+" "+rs.getString("emp_lastname"));
                            Hotel.setCheckIn(new CheckIn());
                            Hotel.setCheckOut(new CheckOut());
                            Hotel.setCustomer(new Customers());
                            Hotel.setReservations(new Reservations());
                            Hotel.setRooms(new Rooms());
                            Hotel.getHome().getTabbebPane().add(Hotel.getCheckIn(),"CHECK_IN");
                            Hotel.getHome().getTabbebPane().add(Hotel.getCheckOut(),"CHECK_OUT");
                            Hotel.getHome().getTabbebPane().add(Hotel.getRooms(),"ROOMS");
                            Hotel.getHome().getTabbebPane().add(Hotel.getReservations(),"RESERVATIONS");
                            Hotel.getHome().getTabbebPane().add(Hotel.getCustomer(),"CUSTOMERS");
                            if(Hotel.getRole().equals("admin"))
                            {
                                Hotel.getHome().setTitle(Hotel.getHome().getTitle()+" (ADMIN)");
                                Hotel.setEmployees(new Employees());
                                Hotel.getHome().getTabbebPane().add(Hotel.getEmployees(),"EMPLOYEES");
                            }
                            Hotel.getHome().setSize(700,550);
                            Hotel.getHome().setLocationRelativeTo(null);
                            Hotel.getHome().setVisible(true);
                            Hotel.getLogin().setVisible(false);
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(this, "Incorrect password");
                            t_password.setText("");
                        }
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "Username does not exist!");
                        t_username.setText("");
                        t_password.setText("");
                    }
                    con.close();
                }
            }catch(ClassNotFoundException | SQLException ex){
                Logger.getLogger(CheckIn.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_b_loginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField t_password;
    private javax.swing.JTextField t_username;
    private javax.swing.JLabel userLogo;
    // End of variables declaration//GEN-END:variables
}
